### PR TITLE
Fix help command URL

### LINKED ISSUE #67: Fix help command URL and message
Create new command specific to Wedding package

### PR DESCRIPTION
**Pull request by hrishikeshsathyian**
Fixes #67

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java [hunk 1]
```diff
@@ -14,7 +14,7 @@
 import seedu.address.logic.commands.EditCommand;
 import seedu.address.logic.commands.ExitCommand;
 import seedu.address.logic.commands.FindCommand;
-import seedu.address.logic.commands.HelpCommand;
+import seedu.address.logic.commands.wedding.HelpCommand;
```
Comment (soonami69) [inline src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java:17]: I think the order of imports is incorrect?

File: src/main/java/seedu/address/model/wedding/UniqueWeddingList.java [hunk 2]
```diff
@@ -103,8 +103,8 @@ private boolean weddingsAreUnique(List<Wedding> weddings) {
         return true;
     }
 
-    @Override
-    public String toString() {
-        return asUnmodifiableObservableList().toString();
-    }
+//    @Override
```
Comment (soonami69) [inline src/main/java/seedu/address/model/wedding/UniqueWeddingList.java:106]: what's the point of this toString method? Is it used for storage?

**Review by soonami69 — CHANGES_REQUESTED** [review]
Please fix style issues

File: src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java (hunk 1 above)
Comment (hrishikeshsathyian) [reply src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java:17]: Yep, you are right. Fixed!

File: src/main/java/seedu/address/model/wedding/UniqueWeddingList.java (hunk 2 above)
Comment (hrishikeshsathyian) [reply src/main/java/seedu/address/model/wedding/UniqueWeddingList.java:106]: I think it has no use , I will remove it from the codebase
