### PR TITLE
Fix clear and enhance filter

### LINKED ISSUE #223: Enable clear 999

### PR DESCRIPTION
**Pull request by Xzh119**

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/wedding/FilterByTagCommandParser.java [hunk 1]
```diff
@@ -22,17 +23,18 @@ public class FilterByTagCommandParser implements Parser<FilterByTagCommand> {
...
-        if (words.length > 1) {
-            throw new ParseException(TOO_MANY_TAGS_MESSAGE);
-        }
-
 
         if (trimArgs.isEmpty()) {
             return new FilterByTagCommand();
         } else {
-            return new FilterByTagCommand(new PersonContainsTagPredicate(trimArgs));
+            List<String> tagKeywords = Arrays.asList(trimArgs.split("\\s+"));
```
Comment (soonami69) [inline src/main/java/seedu/address/logic/parser/wedding/FilterByTagCommandParser.java:30]: Good handling of errors

**Review by soonami69 — APPROVED** [review]
