### PR TITLE
Fix new wedding command

### LINKED ISSUE #101: AlphaTest: Add New Wedding
Should be message for users to know what is left before they complete their draft wedding, so they know how much is left

### LINKED ISSUE #169: [PE-D][Tester E] Message for users to know what is left
Should be message for users to know what is left before they complete their draft wedding, so they know how much is left

After adding the groom, there is no message to add the next person. User is able to leave creation of wedding halfway. 

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: mistyk786/ped#5

### LINKED ISSUE #171: [PE-D][Tester A] Opening another pre-existing wedding while I am creating a new wedding draft does not allow me to add members to the pre-existing wedding
To recreate:

Step 1: Add new wedding via command new

Step 2: Before adding bride and groom to the draft, open another pre-existing wedding instead using the open command (e.g. open 2)

Step 3: Add a new person to the wedding. All new added members go to draft instead of current open wedding at index 2

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: FooNicholas/ped#2

### LINKED ISSUE #173: [PE-D][Tester E] Add command locked to adding members if user stops creating wedding
Due to issue 5, if a user stops creating a wedding, and presses add again, they are stuck with adding a member to a wedding that they are unaware of. There should be a draft mode for users to know if they are in the midst of creating a wedding that restricts them from abandoning creation of a wedding

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: mistyk786/ped#6

### LINKED ISSUE #189: [PE-D][Tester C] Cannot see draft details
after doing new n/NAME d/01012025, we are unable to see what we are adding to.
User is able to carry out other actions and forget about the current draft

a suggestion would be to create a box on the left side with the word draft and allow opening and closing it.

User is also unable to see whether the bridge or the groom has been added already.
 command: add n/bride p/12345 e/12345@gmail.coma/123455 t/bride

suggestion: either prevent the user from doing other actions while creating a new weddng, or create the draft feature for users to see.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Shanyey/ped#15

### LINKED ISSUE #200: [PE-D][Tester B] Edit Command Malfunction After New Command
**Description**: After add a new wedding, using editperson will not cause any result, while the user guide says it should work with active wedding.

**Reproduce**:
1. Add a new wedding using new keyword
2. edit a person using editperson command.

**Expected**: To be determined.

**Actual**: Nothing happened.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Prog-Neuro-Com/ped#6

### PR DESCRIPTION
**Pull request by zedonggg**
### Additions
Changed the process of adding a new wedding to guide the user through adding the bride first then the groom, using LogicMemory to facilitate persistence between the different commands. 

During this process, all other commands are blocked from running other than `exit` to quit the app and `n` to abort the add wedding operation.

Added more descriptive error messages to inform the user what command needs to be added next

### Known bugs
If an invalid command is typed between the wedding creation, it displays the invalid command exception instead of the exception that tells them they are in the middle of creating a wedding. This is due to the limitation of the logic having to parse the command first before executing, and the blocking relies on knowing the instance of the command to execute

Some testcases are broken

### CODE REVIEW

File: src/main/java/seedu/address/logic/LogicManager.java [hunk 1]
```diff
@@ -49,6 +52,12 @@ public CommandResult execute(String commandText) throws CommandException, ParseE
 
         CommandResult commandResult;
         Command command = weddingPlannerParser.parseCommand(commandText);
+
+        if (!(command instanceof AddWeddingPersonCommand || command instanceof ExitCommand
```
Comment (hrishikeshsathyian) [inline src/main/java/seedu/address/logic/LogicManager.java:56]: Maybe we should separate this boolean condition out into some boolean variables to make it more readable

File: src/main/java/seedu/address/logic/commands/wedding/AddWeddingPersonCommand.java [hunk 2]
```diff
@@ -52,10 +57,39 @@ public AddWeddingPersonCommand(Person toAdd) {
...
+
+            Wedding activeWedding = model.getDraftWedding();
+
+            if (model.weddingHasPerson(activeWedding, toAdd)) {
+                throw new CommandException(MESSAGE_DUPLICATE_PERSON + LogicMemory.getDraftingMessage());
+            }
+
+            switch (state) {
+            case ADDING_BRIDE:
+                if (!toAdd.getTags().stream().anyMatch(t -> t.tagName.equalsIgnoreCase("bride"))) {
```
Comment (hrishikeshsathyian) [inline src/main/java/seedu/address/logic/commands/wedding/AddWeddingPersonCommand.java:72]: It might be better to add a comment here to make it more clear what is happening with the streams here. Not sure if it will affect functional LOC, maybe can also remove print statements

**Review by hrishikeshsathyian — CHANGES_REQUESTED** [review]
